# Creating arrays 

In [1]:
import numpy as np

In [2]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [3]:
sample_array.dtype

dtype('int64')

In [8]:
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [10]:
ones.dtype

dtype('float64')

In [11]:
type( ones)

numpy.ndarray

In [14]:
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

## .arange() 

In [18]:
range_array = np.arange(0,10, 2)
range_array

array([0, 2, 4, 6, 8])

## Random.randint() 

In [19]:
random_array = np.random.randint(0, 20, size=(3,5))
random_array

array([[ 8, 14, 11,  1,  1],
       [10, 12, 11, 12,  6],
       [ 4, 16, 13, 14,  1]])

In [20]:
random_array.size

15

In [21]:
random_array.shape

(3, 5)

## Random.random 

In [29]:
random_array_2 = np.random.random((5,3))
random_array_2

array([[0.25911866, 0.82996237, 0.89137838],
       [0.37017359, 0.670067  , 0.12471712],
       [0.27572569, 0.66990844, 0.07343626],
       [0.32546392, 0.89457783, 0.46612476],
       [0.04578273, 0.77239774, 0.39964595]])

In [30]:
random_array_2.shape

(5, 3)

## Random.rand() 

In [32]:
random_array_3 = np.random.rand(5,3)
random_array_3

array([[0.65734793, 0.99599517, 0.97170418],
       [0.32963517, 0.60866853, 0.06396841],
       [0.30799088, 0.51517273, 0.26775578],
       [0.34223465, 0.49605208, 0.28354457],
       [0.43437138, 0.82602058, 0.20178785]])

## random.seed()

Pseudo-random numbers

In [ ]:
np.random.seed()