# Random.seed() 

In [1]:
import numpy as np

In [2]:
sample_array = np.array([1,2,3])

In [3]:
ones = np.ones((2,3))

In [4]:
zeros = np.zeros((2,3))

In [5]:
range_array = np.arange(0,10,2)

In [6]:
random_array = np.random.randint(0,10, size=(3,5))

In [7]:
random_array_2 = np.random.random((5,3))

In [14]:
random_array_3 = np.random.rand(5,3)
random_array_3

array([[0.84589218, 0.45168626, 0.95760681],
       [0.16824128, 0.14532469, 0.14205275],
       [0.61005313, 0.73701629, 0.21840158],
       [0.70618922, 0.04719149, 0.9906542 ],
       [0.30833203, 0.13142269, 0.98697253]])

In [21]:
# Pseudo-random numbers 
np.random.seed( seed=0 )
random_array_4 = np.random.randint(10, size=(5,3) )
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [29]:
np.random.seed( 7 )
random_array_5 = np.random.random((5,3))
random_array_5

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])