# Arrays and Matrices 

Menu:

* [Viewing arrays and matrices](#Viewing-arrays-and-matrices)
    * [Unique](#Unique)

In [3]:
import pandas as pd
import numpy as np

## Viewing arrays and matrices

In [9]:
a1 = np.array([1,2,3])
a2 = np.array( [ [1,2,3], [4,5,6] ] )
a3 = np.array( [ [ [1,2,3],[4,5,6],[7,8,9] ],
               [ [10,11,12], [13,14,15], [16,17,18] ]] )

In [4]:
random_array_4 = np.random.randint( 10, size=(5,3))
random_array_5 = np.random.random((5,3))

### Unique

In [6]:
# Check if there is repeat.
random_array_4

array([[2, 9, 9],
       [6, 1, 8],
       [7, 3, 9],
       [4, 8, 9],
       [0, 1, 4]])

In [8]:
# Now we use the unique function. 
np.unique( random_array_4)

array([0, 1, 2, 3, 4, 6, 7, 8, 9])

### Viewing Index 

In [10]:
a1[0]

1

In [11]:
a2[0]

array([1, 2, 3])

In [12]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
a3[0][0][0]

1

### Slicing

In [15]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [16]:
a3[:2, :2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [18]:
a4 = np.random.randint( 10, size=( 2,3,4,5 ))
a4

array([[[[9, 8, 2, 5, 1],
         [8, 1, 1, 0, 9],
         [5, 0, 6, 6, 5],
         [4, 1, 5, 7, 4]],

        [[9, 7, 7, 6, 8],
         [2, 4, 7, 2, 2],
         [4, 1, 1, 8, 2],
         [4, 8, 6, 3, 2]],

        [[7, 0, 3, 5, 3],
         [3, 1, 4, 2, 6],
         [6, 4, 4, 2, 4],
         [9, 6, 3, 3, 9]]],


       [[[2, 4, 1, 6, 1],
         [9, 1, 0, 1, 8],
         [9, 4, 0, 7, 0],
         [9, 8, 5, 0, 3]],

        [[1, 6, 0, 8, 0],
         [2, 5, 9, 8, 8],
         [7, 5, 1, 2, 0],
         [2, 8, 6, 9, 8]],

        [[6, 1, 1, 6, 4],
         [5, 0, 9, 5, 9],
         [2, 1, 1, 0, 0],
         [3, 6, 0, 6, 7]]]])

In [36]:
# Get the first 4 numbers of the inner most arrays. 
a4[-1:, -1:, :1]

array([[[[6, 1, 1, 6, 4]]]])