# Manipulating Arrays 

In [2]:
import pandas as pd
import numpy as np

In [51]:
a1 = np.array([1,2,3])
a2 = np.array( [ [1,2,3], [4,5,6] ] )
a3 = np.array( [ [ [1,2,3],[4,5,6],[7,8,9] ],
               [ [10,11,12], [13,14,15], [16,17,18] ]] )

In [52]:
ones = np.ones(3)
ones

array([1., 1., 1.])

## Arithmetic 

### Addition

In [11]:
a1

array([1, 2, 3])

In [7]:
a1 + ones

array([2., 3., 4.])

In [12]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
a2 + ones

array([[2., 3., 4.],
       [5., 6., 7.]])

### Substraction

In [13]:
a1

array([1, 2, 3])

In [8]:
a1 - ones

array([0., 1., 2.])

In [14]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
a2 - ones

array([[0., 1., 2.],
       [3., 4., 5.]])

### Multiplication

In [16]:
a1

array([1, 2, 3])

In [9]:
a1 * ones

array([1., 2., 3.])

In [33]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
a1 * a2

array([[ 1,  4,  9],
       [ 4, 10, 18]])

In [21]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [70]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [56]:
a2.shape

(2, 3)

In [57]:
a3.shape

(2, 3, 3)

In [55]:
a2.T.shape

(3, 2)

In [83]:
a2_reshape = a2.reshape((-1,1)) 

In [80]:
a2_reshape

array([[1, 2, 3],
       [4, 5, 6]])

In [84]:
a2_reshape * a3

ValueError: operands could not be broadcast together with shapes (6,1) (2,3,3) 

In [32]:
a2 * a3[0][1]

array([[ 4, 10, 18],
       [16, 25, 36]])

In [53]:
a2.T * a3

ValueError: operands could not be broadcast together with shapes (3,2) (2,3,3) 

### Re-shape 

In [35]:
# How can you re-shape a2 to be compatible with a3? 
np.reshape( a2, (2,3,3))

ValueError: cannot reshape array of size 6 into shape (2,3,3)

## Division 

In [37]:
a1 / ones

array([1., 2., 3.])

In [38]:
a2 / a1

array([[1. , 1. , 1. ],
       [4. , 2.5, 2. ]])

In [41]:
# Floor Division removes the decimals
a2 // a1

array([[1, 1, 1],
       [4, 2, 2]])

## Power 

Power and Square is the same

In [43]:
a2 ** 2

array([[ 1,  4,  9],
       [16, 25, 36]])

##  Squares

In [44]:
np.square(a2)

array([[ 1,  4,  9],
       [16, 25, 36]])

##  NumPy's functions

### Addition

In [45]:
np.add(a1, ones)

array([2., 3., 4.])

## Modulo

In [46]:
a1 % 2

array([1, 0, 1])

In [47]:
np.mod( a1, 2)

array([1, 0, 1])

In [48]:
a2 % 2

array([[1, 0, 1],
       [0, 1, 0]])

## Exponential

In [49]:
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])

## Log

In [50]:
np.log( a1 )

array([0.        , 0.69314718, 1.09861229])