# Arithmetic Part 2 

In [1]:
import pandas as pd 
import numpy as np

In [2]:
a1 = np.array([1,2,3])
a2 = np.array( [ [1,2,3], [4,5,6] ] )
a3 = np.array( [ [ [1,2,3],[4,5,6],[7,8,9] ],
               [ [10,11,12], [13,14,15], [16,17,18] ]] )

In [3]:
ones = np.ones(3)
ones

array([1., 1., 1.])

## Aggregation

It is performing the same operation on a number of things, in this case, numpy's arrays. 

### Normal List from Python

In [4]:
listy_list = [1,2,3]
type( listy_list)

list

In [5]:
sum( listy_list)

6

### Numpy Ndarray

In [6]:
a1

array([1, 2, 3])

In [7]:
type(a1)

numpy.ndarray

In [8]:
sum(a1)

6

In [9]:
np.sum(a1)

6

Use Python's methods (`sum()`) on Python datatypes and use Numpy's methods on Numpy arrays (`np.sum()`)

In [10]:
# Create a masive numpy array
massive_array = np.random.random(1000)
massive_array

array([7.61711311e-01, 5.29368220e-01, 3.83229388e-01, 8.10542013e-01,
       9.01137694e-01, 9.50932850e-01, 4.93197547e-02, 6.60298800e-01,
       2.83438478e-01, 1.58922180e-01, 2.46624047e-01, 6.41417970e-01,
       3.50847988e-01, 5.59879356e-01, 2.68494149e-01, 5.13696900e-02,
       3.68078502e-01, 5.59877938e-01, 4.17430625e-01, 2.72534490e-01,
       8.49407865e-01, 9.14649522e-01, 3.40890318e-01, 4.70532605e-01,
       2.06667242e-02, 1.24622254e-04, 9.83840555e-01, 1.42603584e-01,
       3.35510007e-01, 8.73544296e-01, 4.61307827e-01, 9.79757808e-01,
       6.11686187e-01, 5.77548344e-01, 8.39752970e-01, 9.01083249e-02,
       8.46131044e-01, 8.66739635e-01, 8.51716456e-01, 9.33592452e-01,
       7.71695400e-01, 6.16152879e-01, 5.94185302e-01, 6.98786290e-02,
       4.74879045e-01, 3.17025174e-02, 4.74987827e-01, 3.86656673e-01,
       5.72099193e-01, 9.85285815e-01, 5.84092835e-01, 9.54878916e-01,
       6.90499810e-01, 2.42575185e-01, 4.15176636e-01, 1.78899813e-01,
      

In [11]:
massive_array.size

1000

In [12]:
massive_array[:100]

array([7.61711311e-01, 5.29368220e-01, 3.83229388e-01, 8.10542013e-01,
       9.01137694e-01, 9.50932850e-01, 4.93197547e-02, 6.60298800e-01,
       2.83438478e-01, 1.58922180e-01, 2.46624047e-01, 6.41417970e-01,
       3.50847988e-01, 5.59879356e-01, 2.68494149e-01, 5.13696900e-02,
       3.68078502e-01, 5.59877938e-01, 4.17430625e-01, 2.72534490e-01,
       8.49407865e-01, 9.14649522e-01, 3.40890318e-01, 4.70532605e-01,
       2.06667242e-02, 1.24622254e-04, 9.83840555e-01, 1.42603584e-01,
       3.35510007e-01, 8.73544296e-01, 4.61307827e-01, 9.79757808e-01,
       6.11686187e-01, 5.77548344e-01, 8.39752970e-01, 9.01083249e-02,
       8.46131044e-01, 8.66739635e-01, 8.51716456e-01, 9.33592452e-01,
       7.71695400e-01, 6.16152879e-01, 5.94185302e-01, 6.98786290e-02,
       4.74879045e-01, 3.17025174e-02, 4.74987827e-01, 3.86656673e-01,
       5.72099193e-01, 9.85285815e-01, 5.84092835e-01, 9.54878916e-01,
       6.90499810e-01, 2.42575185e-01, 4.15176636e-01, 1.78899813e-01,
      

In [14]:
%timeit sum(massive_array) # Python's function sum()
%timeit np.sum(massive_array) # Numpy's function np.sum()

74.5 µs ± 2.5 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
3.48 µs ± 19.2 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [15]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
np.mean(a2)

3.5

In [17]:
np.max(a2)

6

In [18]:
np.min(a2)

1

In [22]:
# Standar Deviation = It's  a mesure to how spread out a group of numbers is from the mean. 
np.std(a2)

1.707825127659933

In [23]:
# Variance = Measure of the average degree to which each number is different to the mean. 
# Higher variance = wider range of numbers.
# Lower variance = Lower range of numbers. 
np.var(a2)

2.9166666666666665

In [25]:
# Standard Deviation = squareroot of variance
np.sqrt(np.var(a2))

1.707825127659933